name: 🚀 Deploy to Dev

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Dev (Auto)
    runs-on: ubuntu-latest
    env:
      ENV_NAME: dev
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load environment file
        run: |
          echo "Using environment: $ENV_NAME"
          cp .env.$ENV_NAME .env

      - name: Install dependencies & run tests with coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pytest --cov=maths --cov-report=term --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ${{ matrix.python-version }}-${{ env.ENV_NAME }}
