name: 🚀 Deploy to Production

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Type deploy-prod to continue"
        required: true
        default: "deploy-prod"

jobs:
  deploy-prod:
    if: ${{ github.event.inputs.action == 'deploy-prod' }}
    name: Deploy to Prod (Manual)
    runs-on: ubuntu-latest
    env:
      ENV_NAME: prod
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load environment file
        run: |
          cp .env.prod .env

      - name: Install dependencies & run tests with coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pytest --cov=maths --cov-report=term --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ${{ matrix.python-version }}-${{ env.ENV_NAME }}